### ISSUE TITLE
QUADINT_TOZXY and QUADINT_FROMZXY do not detect invalid QUADINT nor ZXY

### ISSUE THREAD

**Issue by francois-baptiste** [CartoDB/analytics-toolbox-core#239]
```SELECT `carto-un.carto.QUADINT_TOZXY`(32)```

```SELECT`carto-un.carto.QUADINT_FROMZXY`(0,0,1)```

return a result even if these QUADINT or ZXY are invalid.

It would be great to protect these functions against this (might have an overall performance impact) or to create  `IS_VALID_QUADINT` and `IS_VALID_ZXY` functions.

**Comment by Jesus89** [comment]
We are going to reframe the strategy around quadint. We will take into account the IS_VALID check for that
