### ISSUE TITLE
Error when executing H3_CENTER

### ISSUE THREAD

**Issue by alepuccetti** [CartoDB/analytics-toolbox-core#245]
When running a query using `carto-os-eu.carto.H3_CENTER`(h3_key)` BigQuery return this error: `TypeError: h3Lib.h3ToGeo is not a function at UDF$1(STRING) line 10, columns 25-26`

**Comment by alepuccetti** [comment]
I am seeing a very weird behaviour. If I run your example it works for me too. However, If I in certain case I get the failure.

Working query:
```sql
select
    e.h3_key,
    `carto-os-eu`.carto.H3_CENTER(e.h3_key) as h3_center,
    st_centroid(`carto-os-eu`.carto.H3_BOUNDARY(e.h3_key)) as h3_boundary_centroid,
from my_table as e
```

Another working query:
```sql
select
    e.datestamp,
    e.h3_key,
    `carto-os-eu`.carto.H3_CENTER(e.h3_key) as h3_center,
    st_centroid(`carto-os-eu`.carto.H3_BOUNDARY(e.h3_key)) as h3_boundary_centroid,
from my_table as e
join my_other_table as c
    on st_dwithin(`carto-os-eu`.carto.H3_CENTER(e.h3_key), c.geography, c.buffer)
```

However if I use the same code in a more complex query:
```sql
select
    e.datestamp,
    c.centre_id,
    e.h3_key,
    `huq-library.cse__h3.ST_BOUNDARY`(e.h3_key) as h3_geography,
    `carto-os-eu.carto.H3_CENTER`(e.h3_key) as h3_centroid,
    count(*) as total
from my_table as e
join my_other_table as c
    on st_dwithin(`carto-os-eu.carto.H3_CENTER`(e.h3_key), c.geography, c.buffer)
where e.datestamp between "2019-01-02" and "2019-01-02"
group by 1, 2, 3
```
I get the error:
```
TypeError: h3Lib.h3ToGeo is not a function at UDF$1(STRING) line 10, columns 25-26
```

Funny enough this error does not happen if I do the join over the following clause:
```
on st_dwithin(st_centroid(`carto-os-eu`.carto.H3_BOUNDARY(e.h3_key)), c.geography, c.buffer)
``` 

It seems that `H3_CENTER` starts throwing errors when used in join but not always, when I also add the group by. However, using `H3_BOUNDARY` in the same query does not.

Any idea why this is happening?

**Comment by alepuccetti** [comment]
Any news on this issue? I am still experiencing this issue

**Comment by Jesus89** [comment]
Hi, I wasn't able to reproduce the issue. Maybe related to the usage of `huq-library.cse__h3.ST_BOUNDARY`.

Could you try this one?

```sql
select
    e.datestamp,
    c.centre_id,
    e.h3_key,
    `carto-os-eu.carto.H3_BOUNDARY`(e.h3_key) as h3_geography,
    `carto-os-eu.carto.H3_CENTER`(e.h3_key) as h3_centroid,
    count(*) as total
from my_table as e
join my_other_table as c
    on st_dwithin(`carto-os-eu.carto.H3_CENTER`(e.h3_key), c.geography, c.buffer)
where e.datestamp between "2019-01-02" and "2019-01-02"
group by 1, 2, 3
```

**Comment by alepuccetti** [comment]
Hi ,

Sorry `huq-library.cse__h3.ST_BOUNDARY` was a typo, I tested it with thee `carto-os` function and I was getting that error too. I just tested again and I don't get this error.

I just re-run my tests and the error is not present anymore. I will close this.

@Jesus89 Is it possible that the functions were updated this error was fixed by the update?
