### ISSUE TITLE
Redshift S2_BOUNDARY returning incorrect boundary

### ISSUE THREAD

**Issue by dtomko** [CartoDB/analytics-toolbox-core#287]
It appears as thought the boundary is formatted as POINT(LATITUDE LONGITUDE) instead of POINT(LONGITUDE LATITUDE) which results in a s2 cell from Maine appearing in Alaska.

<img width="842" alt="Screen Shot 2022-08-11 at 12 33 43 PM" src="https://user-images.githubusercontent.com/563468/184184288-8745709c-de97-4570-b900-aa5d89e95a2c.png">

**Comment by Jesus89** [comment]
Yes, there is a bug in the implementation. We will fix it in a future release.

**Comment by Jesus89** [comment]
Fixed in release '2022.08.19'
