### ISSUE TITLE
Core functions no longer available on Snowflake

### ISSUE THREAD

**Issue by iasymmetric** [CartoDB/analytics-toolbox-core#318]
On Snowflake, all UDFs have disappeared from the carto schema and are no longer available in the data share. The functions were working as recently as yesterday, so this seems to be a new issue.

**Comment by Jesus89** [comment]
@iasymmetric what's the name of the listing you are using?

**Comment by Jesus89** [comment]
OK, thanks. So you are using the active listing. We have forced running the replications. Could you try again, please?

**Comment by iasymmetric** [comment]
They're still gone. I've tried dropping and recreating the shared DB as well and that doesn't fix it either. One thing that's still there though is the sample data in the public schema.

**Comment by Jesus89** [comment]
Hi. Could you check again?

**Comment by iasymmetric** [comment]
@Jesus89 I can see all the functions again and everything seems to be working properly. Thank you!

**Comment by Jesus89** [comment]
Great. Thanks to you!
