### ISSUE TITLE
Sporadic failure of Snowflake user defined functions in the carto h3 module 

### ISSUE THREAD

**Issue by larssnek** [CartoDB/analytics-toolbox-core#336]
**Describe the bug**
We use the carto h3 module in Snowflake. We are using dbt and often when updating a model using the carto h3 module the user-defined functions are not available, but upon rerunning they suddenly are available.

As far as I can tell there is no pattern to when this happens and not. See my screenshot for two consecutive runs where one failed and one was successful. Nothing has changed between the runs and they should both have been successful.

**To Reproduce**
Hard to reproduce as this happens sporadic. I have been running a query in the Snowflake UI as well to try to reproduce. When running the following command it first failed and then it suddenly worked. Nothing changed in between

```sql
select sfcarto.carto.h3_fromlonglat(1, 2, 9);
```

**Expected behavior**
I expect this to always be successful.

**Screenshots**
![image](https://user-images.githubusercontent.com/25799512/194573320-d896e605-6113-4868-8015-be623ade726d.png)

**Additional context**
N/A

**Comment by Jesus89** [comment]
Hello @larssnek

The listing `SFCARTO` was deprecated some months ago, so probably it's not fully available nowadays.

I recommend using the current listing of the "Analytics Toolbox": https://app.snowflake.com/marketplace/listing/GZT0ZKUCHJO. Instead of `SFCARTO`, the database is called `CARTO_OS` and it's active and maintained.

**Comment by larssnek** [comment]
Hi, @Jesus89! I should probably have mentioned that we did this change. This is the `CARTO_OS` database, I've just renamed it to `SFCARTO` :sweat_smile: By the way I also think that e.g. the udf `h3_fromlonglat` has been renamed from the old `SFCARTO` listing to the  new `CARTO_OS` listing, so this wouldn't have worked on the old one.

So the issue is still valid, could you please look into this?

Adding a screenshot from the link you sent me as "proof" it is installed and just renamed :+1: 
![image](https://user-images.githubusercontent.com/25799512/194822059-2f9c4ac4-1750-4ed7-b519-998e9ee5a3e0.png)

**Comment by larssnek** [comment]
@Jesus89, we are experiencing the same behavior still. It's been a lot of fails the last two days, have you been doing deployments recently or is it due to something else?

**Comment by Jesus89** [comment]
Hi @larssnek, sorry for the inconvenience. There was a bug in the deployment system and there was a deployment two days ago without the updates in the share.

The good news is that the bug is fixed, and the shares should be restored.
