### ISSUE TITLE
Snowflake ST_DELAUNAYPOLYGONS error with aggregation

### ISSUE THREAD

**Issue by scoddou** [CartoDB/analytics-toolbox-core#465]
**Describe the bug**
Hello! I am getting the following error when using `ST_DELAUNAYPOLYGONS` with aggregation, but not while using `ST_VORONOIPOLYGONS` with aggregation. Reproducible example below using CARTO Snowflake documentation.

`Invalid aggregate function in ON clause [ARRAY_AGG(CORRELATION(CORRELATION(DATA.POINT)))]`

**To Reproduce**
```sql
;-- RUNS: ST_VORONOIPOLYGONS

SELECT CARTO.CARTO.ST_VORONOIPOLYGONS(
  ARRAY_CONSTRUCT(
    ST_ASGEOJSON(ST_POINT(-75.833, 39.284))::STRING,
    ST_ASGEOJSON(ST_POINT(-75.6, 39.984))::STRING,
    ST_ASGEOJSON(ST_POINT(-75.221, 39.125))::STRING,
    ST_ASGEOJSON(ST_POINT(-75.521, 39.325))::STRING
  )
)

;-- RUNS: ST_VORONOIPOLYGONS

WITH 

DATA AS (
    SELECT ST_ASGEOJSON(ST_POINT(-75.833, 39.284))::STRING POINT UNION ALL
    SELECT ST_ASGEOJSON(ST_POINT(-75.6, 39.984))::STRING  POINT UNION ALL
    SELECT ST_ASGEOJSON(ST_POINT(-75.221, 39.125))::STRING  POINT UNION ALL
    SELECT ST_ASGEOJSON(ST_POINT(-75.521, 39.325))::STRING  POINT 
)

SELECT CARTO.CARTO.ST_VORONOIPOLYGONS(ARRAY_AGG(POINT))
FROM DATA
GROUP BY ALL

;-- RUNS: ST_DELAUNAYPOLYGONS

SELECT CARTO.CARTO.ST_DELAUNAYPOLYGONS(
  ARRAY_CONSTRUCT(
    ST_ASGEOJSON(ST_POINT(-75.833, 39.284))::STRING,
    ST_ASGEOJSON(ST_POINT(-75.6, 39.984))::STRING,
    ST_ASGEOJSON(ST_POINT(-75.221, 39.125))::STRING,
    ST_ASGEOJSON(ST_POINT(-75.521, 39.325))::STRING
  )
)

;-- DOES NOT RUN: ST_DELAUNAYPOLYGONS Invalid aggregate function in ON clause [ARRAY_AGG(CORRELATION(CORRELATION(DATA.POINT)))]


WITH 

DATA AS (
    SELECT ST_ASGEOJSON(ST_POINT(-75.833, 39.284))::STRING POINT UNION ALL
    SELECT ST_ASGEOJSON(ST_POINT(-75.6, 39.984))::STRING  POINT UNION ALL
    SELECT ST_ASGEOJSON(ST_POINT(-75.221, 39.125))::STRING  POINT UNION ALL
    SELECT ST_ASGEOJSON(ST_POINT(-75.521, 39.325))::STRING  POINT 
)

SELECT CARTO.CARTO.ST_DELAUNAYPOLYGONS(ARRAY_AGG(POINT))
FROM DATA
GROUP BY ALL

**Comment by vdelacruzb** [comment]
Hi @scoddou,

Thanks for getting in contact with us and for isolation this issue.

Unfortunately  we are facing a Snowflake limitation on this function.

Even if you refactor your query to:
```
WITH 
DATA AS (
    SELECT ST_ASGEOJSON(ST_POINT(-75.833, 39.284))::STRING POINT UNION ALL
    SELECT ST_ASGEOJSON(ST_POINT(-75.6, 39.984))::STRING  POINT UNION ALL
    SELECT ST_ASGEOJSON(ST_POINT(-75.221, 39.125))::STRING  POINT UNION ALL
    SELECT ST_ASGEOJSON(ST_POINT(-75.521, 39.325))::STRING  POINT 
),
AGGREGATED AS (
    SELECT ARRAY_AGG(POINT) geog_array FROM DATA
    GROUP BY ALL
)
SELECT CARTO.CARTO.ST_DELAUNAYPOLYGONS(geog_array)
FROM AGGREGATED;
-- Unsupported subquery type cannot be evaluated
```

Also if your data is contained in a table it will fail:
```
CREATE TABLE MY_DB.MY_SCHEMA.DELANUAY_TEST AS
SELECT ARRAY_CONSTRUCT(
    ST_ASGEOJSON(ST_POINT(-75.833, 39.284))::STRING,
    ST_ASGEOJSON(ST_POINT(-75.6, 39.984))::STRING,
    ST_ASGEOJSON(ST_POINT(-75.221, 39.125))::STRING,
    ST_ASGEOJSON(ST_POINT(-75.521, 39.325))::STRING
) geog_array;

SELECT CARTO.CARTO.ST_DELAUNAYPOLYGONS(geog_array)
FROM MY_DB.MY_SCHEMA.DELANUAY_TEST;
-- Unsupported subquery type cannot be evaluated
```

It is produced by the DELAUNAY functions having some unnesting and aggregations inside, so these functions do not work with tables or subqueries.

We were conscious about this topic and it was reported directly to the Snowflake team some time ago. As can be seen [here](https://community.snowflake.com/s/question/0D50Z00008BDZz0SAH/subquery-in-select-clause) it was present since long time ago so might not be that easy to solve from their side.

We will need to explore other possible implementations of the function in order to solve this problem.

**Comment by scoddou** [comment]
Thank you for checking into this @vdelacruzb. I will close if this is a limitation on the Snowflake side. But a couple of follow-up questions:

Is Delaunay dependent on Voronoi being calculated first? If so, could Delaunay and Voronoi be calculated independently?

I also noticed that d3-voronoi has a depreciation notice on their github. Do the Voronoi functions use d3-delaunay?

``Deprecation notice: Consider using the newer [d3-delaunay](https://github.com/d3/d3-delaunay) instead of d3-voronoi. Based on [Delaunator](https://github.com/mapbox/delaunator), d3-delaunay is 5-10× faster than d3-voronoi to construct the Delaunay triangulation or the Voronoi diagram, is more robust numerically, has Canvas rendering built-in, allows traversal of the Delaunay graph, and a variety of other improvements.
``

Thank you again for looking into this!

**Comment by vdelacruzb** [comment]
Hi @scoddou,

At this moment both Delaunay and Voronoi UDFs use the [turf-voronoi](https://turfjs.org/docs/#voronoi) ([github](https://github.com/Turfjs/turf/tree/master/packages/turf-voronoi)).

Given your comment I'll create an internal ticket to explore performance and split the implementation to make Delaunay not dependant on Voronoi.

Thanks for checking about potential improvements.

**Comment by scoddou** [comment]
@vdelacruzb thank you for the additional documentation behind the Voronoi implementation. It looks like their GitHub mentions 

``The Voronoi algorithim used comes from the d3-voronoi package`` 

But I can check if there are any commits to upgrade to d3-delaunay

Also, after checking turf’s functions, it looks like `tin` is their implementation of Delaunay [here](https://github.com/maral/turf/tree/7d7b3756fdf0b94ae60ec9ebbc19f4b788f37f86/packages/turf-tin) (in case Voronoi and Delaunay can be split on Snowflake)

Thank you again for the help

**Comment by scoddou** [comment]
For anyone that lands on this post: turf is actively working on testing updates for Voronoi [discussed here](https://github.com/Turfjs/turf/pull/1043)
